require:
  - rubocop
  - rubocop-rails
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

Style/FrozenStringLiteralComment:
  EnforcedStyle: never