require:
  - rubocop
  - rubocop-rails
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
    - "Gemfile"

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/NestedGroups:
  MaxNesting: 4

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
